import { createSlice } from '@reduxjs/toolkit';

const today = new Date();

const initialState = {
  date:
    today.getFullYear() +
    '-' +
    String(today.getMonth() + 1).padStart(2, '0') +
    '-' +
    String(today.getDate()).padStart(2, '0'),
  filter: {
    sport: [],
    channel: [],
  },
  selectedPlatform: localStorage.getItem('selectedPlatform')
    ? localStorage.getItem('selectedPlatform')
    : 'TV',
  translations: {
    EN: {
      Sports: 'Sports',
      Channels: 'Channels',
      Football: 'Football',
      Basketball: 'Basketball',
      MMA: 'ММА',
      Boxing: 'Boxing',
      Racing: 'Racing',
      Tennis: 'Tennis',
      Hockey: 'Hockey',
      Darts: 'Darts',
      Futsal: 'Futsal',
      Athletics: 'Athletics',
      Karate: 'Karate',
      Documentary: 'Documentary',
      Georgia: 'Georgia',
      Azerbaijan: 'Azerbaijan',
      Kazakhstan: 'Kazakhstan',
      Kyrgyzstan: 'Kyrgyzstan',
      Latvia: 'Latvia',
      Lithuania: 'Lithuania',
      Moldova: 'Moldova',
      Ukraine: 'Ukraine',
      Uzbekistan: 'Uzbekistan',
      Philippines: 'Philippines',
      Tajikistan: 'Tajikistan',
      Turkmenistan: 'Turkmenistan',
      Estonia: 'Estonia',
      Belarus: 'Belarus',
      Armenia: 'Armenia',
      'Setanta Sports 1': 'Setanta Sports 1',
      'Setanta Sports 2': 'Setanta Sports 2',
      'Setanta Sports 3': 'Setanta Sports 3',
      'Setanta Ukraine': 'Setanta Ukraine',
      'Setanta Ukraine +': 'Setanta Ukraine +',
      'Setanta Kazakhstan': 'Setanta Kazakhstan',
      'Setanta Kyrgyzstan': 'Setanta Kyrgyzstan',
      'Setanta Moldova': 'Setanta Moldova',
      'Setanta Philippines': 'Setanta Philippines',
      'Watch Now': 'Watch Now',
      TV: 'TV',
      APP: 'APP',
      Watch: 'Watch',
      Home: 'Home',
      News: 'News',
      Scores: 'Scores',
      'Premier League': 'Premier League',
      Bundesliga: 'Bundesliga',
      'La Liga': 'La Liga',
      'Serie A': 'Serie A',
      'Ligue 1': 'Ligue 1',
    },
    RU: {
      Sports: 'Спорт',
      Channels: 'Каналы',
      Football: 'Футбол',
      Basketball: 'Баскетбол',
      MMA: 'ММА',
      Boxing: 'Бокс',
      Racing: 'Гонки',
      Tennis: 'Теннис',
      Hockey: 'Хоккей',
      Darts: 'Дартс',
      Futsal: 'Футзал',
      Athletics: 'Легкая атлетика',
      Karate: 'Каратэ',
      Documentary: 'Документальный',
      Georgia: 'Грузия',
      Azerbaijan: 'Азербайджан',
      Kazakhstan: 'Казахстан',
      Kyrgyzstan: 'Кыргызстан',
      Latvia: 'Латвия',
      Lithuania: 'Литва',
      Moldova: 'Молдова',
      Ukraine: 'Украина',
      Uzbekistan: 'Узбекистан',
      Philippines: 'Филиппины',
      Tajikistan: 'Таджикистан',
      Turkmenistan: 'Туркменистан',
      Estonia: 'Эстония',
      Belarus: 'Беларусь',
      Armenia: 'Армения',
      'Setanta Sports 1': 'Setanta Sports 1',
      'Setanta Sports 2': 'Setanta Sports 2',
      'Setanta Sports 3': 'Setanta Sports 3',
      'Setanta Ukraine': 'Setanta Ukraine',
      'Setanta Ukraine +': 'Setanta Ukraine +',
      'Setanta Kazakhstan': 'Setanta Kazakhstan',
      'Setanta Kyrgyzstan': 'Setanta Kyrgyzstan',
      'Setanta Moldova': 'Setanta Moldova',
      'Setanta Philippines': 'Setanta Philippines',
      'Watch Now': 'Смотреть сейчас',
      TV: 'Каналы',
      APP: 'Платформа',
      Watch: 'Смотреть',
      Home: 'Главная',
      News: 'Новости',
      Scores: 'Результаты',
      'Premier League': 'Премьер-лига',
      Bundesliga: 'Бундеслига',
      'La Liga': 'Ла Лига',
      'Serie A': 'Серия А',
      'Ligue 1': 'Лига 1',
    },
    KA: {
      Sports: 'სპორტი',
      Channels: 'არხები',
      Football: 'ფეხბურთი',
      Basketball: 'კალათბურთი',
      MMA: 'ММА',
      Boxing: 'კრივი',
      Racing: 'რბოლა',
      Tennis: 'ტენისი',
      Hockey: 'ჰოკეი',
      Darts: 'დარტსი',
      Futsal: 'ფუტსალი',
      Karate: 'კარატე',
      Athletics: 'მძლეოსნობა',
      Documentary: 'დოკუმენტური',
      Georgia: 'საქართველო',
      Azerbaijan: 'აზერბაიჯანი',
      Kazakhstan: 'ყაზახეთი',
      Kyrgyzstan: 'ყირგიზეთი',
      Latvia: 'ლატვია',
      Lithuania: 'ლიტვა',
      Moldova: 'მოლდოვა',
      Ukraine: 'უკრაინა',
      Uzbekistan: 'უზბეკეთი',
      Philippines: 'ფილიპინები',
      Tajikistan: 'ტაჯიკეთი',
      Turkmenistan: 'თურქმენეთი',
      Estonia: 'ესტონეთი',
      Belarus: 'ბელარუსი',
      Armenia: 'სომხეთი',
      'Setanta Sports 1': 'Setanta Sports 1',
      'Setanta Sports 2': 'Setanta Sports 2',
      'Setanta Sports 3': 'Setanta Sports 3',
      'Setanta Ukraine': 'Setanta Ukraine',
      'Setanta Ukraine +': 'Setanta Ukraine +',
      'Setanta Kazakhstan': 'Setanta Kazakhstan',
      'Setanta Kyrgyzstan': 'Setanta Kyrgyzstan',
      'Setanta Moldova': 'Setanta Moldova',
      'Setanta Philippines': 'Setanta Philippines',
      'Watch Now': 'უყურე ახლა',
      TV: 'ტელევიზია',
      APP: 'აპლიკაცია',
      Watch: 'უყურე',
      Home: 'მთავარი',
      News: 'სიახლეები',
      Scores: 'შედეგები',
      'Premier League': 'პრემიერ ლიგა',
      Bundesliga: 'ბუნდესლიგა',
      'La Liga': 'ლა ლიგა',
      'Serie A': 'სერია ა',
      'Ligue 1': 'ლიგა 1',
    },
  },
};

const clientSlice = createSlice({
  name: 'client',
  initialState,
  reducers: {
    setWeek: (state, action) => {
      state.date = action.payload;
    },
    updateFilter: (state, action) => {
      const { filterId, value, add } = action.payload;

      if (!state.filter[filterId].includes(value) && add) {
        state.filter[filterId].push(value);
      } else if (!add) {
        state.filter[filterId] = state.filter[filterId].filter(
          (name) => name !== value
        );
      }
    },
    selectPlatform: (state, action) => {
      state.selectedPlatform = action.payload;
    },
  },
});

export const { setWeek, updateFilter, selectPlatform } = clientSlice.actions;
export default clientSlice.reducer;
